stages:
  - test

unit-integration-test-job: # This job runs in the test stage.
  stage: test # It only starts when the job in the build stage completes successfully.
  before_script:
    - dart pub get
  script:
    - dart test
  tags:
    - test
